/*!
 * Copyright (c) 2023 Digital Bazaar, Inc. All rights reserved.
 */
export const mockKey = {
  type: 'Multikey',
  publicKeyMultibase: 'zynkLvFajqEANBYZ7BbjYfjZWEKxC2o1cFWbvsK4XzSDyjJ6Unze3XNAvBNKkfCPRHAEQY',
  secretKeyMultibase: 'zEbERsR7stKyp26JemimwCrTcd26myURp5YZaQ5ahCwWnatvLfjxnrmsX1cTU2eH1fpfY'
};

export const suites = [
  {
    title: 'verifies with key & signature produced in node',
    // this was generated by the node key generator
    key: {
      type: 'Multikey',
      publicKeyMultibase: 'zynkWQ2LUf58H4VwLGjscwb9KJwGUmqBFXdJKnCXxDMciFXioY7Hq7MvEdVfsBiQSVa9k9',
      secretKeyMultibase: 'zEbCcd62anxNxioGCdP818UobJn1oEmgL5PHUvQ5AvdyVeLJxeJ4Kr73RqqvG5DN7Zq48',
    },
    signature: 'ugUT6wkoPbte5yNVPkN8dgW1FxZwhaCSLKjPDYGHjqpGZxN1gwn8wKESb6cPfRvpyX8Nw8G8ZReSrTigaN' +
      'xahDvhLMpKN4kWiLuRSCtU9ojjZCUbjgN6myryLcV16ZRKAUT',
    data: 'node key test'
  },
  {
    title: 'verifies with key & signature produced in browser',
    // this was generated in chrome using stablelib
    key: {
      type: 'Multikey',
      publicKeyMultibase: 'zynkTJniuGEdomzqyLAnnbZVgPxY24bD7ror4xCF8S86gVbUiew2jPPe1P3y8xi98J1jCT',
      secretKeyMultibase: 'zEbEtgGMEq2cogS8RtCrKCP1C5iuznnNg977LRksnE8tt28gEoM4LEP4uiuoyLzG287wr'
    },
    signature: '2LBGHCDXxFMGq6PxTpYU5Bhwfy13EUJmgu57pnm1NdpGtvgShPwbnp2uUsXdMupRCyyiWVEi8RWjaa2C2k' +
      'pbx5fuU6tqKe9fnqytHyykJQwKbvcx3zAj2pMNGNaDDGmmhyjZ',
    data: 'browser key test'
  }
];
