/*!
 * Copyright (c) 2023 Digital Bazaar, Inc. All rights reserved.
 */
export const mockKey = {
  type: 'Multikey',
  publicKeyMultibase: '',
  secretKeyMultibase: ''
};

export const suites = [
  {
    title: 'verifies with key & signature produced in node',
    // this was generated by the node key generator
    key: {
      type: 'Multikey',
      publicKeyMultibase: '',
      secretKeyMultibase: '',
    },
    signature: '',
    data: 'node key test'
  },
  {
    title: 'verifies with key & signature produced in browser',
    // this was generated in chrome using stablelib
    key: {
      type: 'Multikey',
      publicKeyMultibase: '',
      secretKeyMultibase: ''
    },
    signature: '',
    data: 'browser key test'
  }
];

export const seed = '';
